version: "3.9"

volumes:
  db_data: {}  # volume для SQLite

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8003:8003"
    environment:
      - DJANGO_DEBUG=1
    volumes:
      - db_data:/app/db.sqlite3
    restart: always

