version: "3.9"

volumes:
  db_data: {}

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=1
    volumes:
      - db_data:/app/db.sqlite3
    restart: always

